label chapter_1_1:
    
    scene bg school_hallway
    with dissolve

    narrator "The school is already starting to get empty."
    narrator "Most of the classroon are dark."
    chloe "It's weird being here this late."
    mc "It's five thirty."
    ethan "That's late for us."
    michael "Speak for yourself."
    chloe "You're literally scared of the dark."
    michael "I'm not scared of the dark."
    mc "You screamed when the lights went out yesterday."
    michael "Because Ethan was standing behind me."
    ethan "I said sorry."
    michael "You whispered 'boo' directly into my ear."
    ethan "It was funny."
    michael "You nearly died."
    ethan "Worth it."
    mc "This is why none of you are allowed to make decisions."
    chloe "You're one to talk."
    narrator "All three of them stare at me."
    mc "..What?"
    michael "Nothing."
    ethan "Absolutely nothing."
    chloe "Keep telling yourself that."
    menu:
        "As what they're staring at.":
            mc "Okay, seriously. What?"
            chloe "Nothing."
            mc "You all said that."
            michael "Because it's nothing."
            ethan "You're being paranoid."
            mc "I'm surrounded by suspicious people."
        "Ignore them.":
            mc "Whatever."
            narrator "I adjust my bag and keep walking."
            ethan "See? They know we're right."
            mc "I can still hear you."
        "Accues Ethan.":
            mc "Ethan."
            ethan "What?"
            mc "What did you do?"
            ethan "Nothing."
            mc "That's exactly what someone who did something would say."
            ethan "I hate how predictable you are."
    scene bg clubroom
    with dissolve
    narrator "We finally reach the club room."
    narrator "The door creaks open."
    mc "Okay."
    mc "We clean for ten minutes."
    mc "Then we leavr."
    michael "Twenty."
    mc "Ten."
    michael "Fifteen."
    mc "Twelve."
    michael "Deal."
    ethan "Why are you negotitating like this is a hostage situation?"
    mc "Because it is."
    narrator "Chloe picks up a stack of papers."
    chloe "Who left all these everywhere?"
    ethan "Probably you."
    chloe "Why would I do that?"
    ethan "I don't know."
    chloe "Great arguement."
    ethan "Thank you."
    narrator "Maya opens a cabinet."
    maya "Why are there thirty-seven glue sticks in here?"
    mc "Energency supplies."
    maya "For what emergency?"
    mc "Glue emergency."
    chloe "That's not a thing."
    mc "Not with that attitude."
    narrator "Ethan picks up a tiny plastic skeleton from one of the shelves."
    ethan "Guys."
    michael "What?"
    ethan "I found our club mascot."
    chloe "Put that down."
    ethan "Why?"
    chloe "It looks cursed."
    mc "It's a plastic skeleton."
    chloe "Exactly."
    ethan "I'm calling him Gregory."
    michael "We're not naming the skeleton."
    ethan "Gregory."
    mc "He looks like a Greg."
    maya "Don't encourage him."
    narrator "Ethan places the skeleton on the desk."
    ethan "Gregory is staying."
    michael "Fine."
    chloe "I'm leaving."
    mc "You can't."
    chloe "Watch me."
    narrator "She walks toward the door."
    narrator "The door suddenly swings shut."
    chloe "..."
    ethan "..."
    maya "..."
    mc "..."
    narrator "A beat of silence."
    ethan "Okay."
    ethan "That was dramatic."
    chloe "Someone pushed it."
    mc "Probably."
    michael "Probably?"
    mc "It's an old door."
    narrator "Chloe opens it again."
    narrator "Nothing happens."
    chloe "See?"
    ethan "Ghost."
    chloe "Shut up."
    ethan "Gregory did it."
    michael "I hate all of you."
    mc "You love us."
    michael "Unfortunately."
    narrator "We finish cleaning."
    narrator "By the time we're done, the sky outside has turned dark."
    michael "Okay, everyone grab your stuff."
    ethan "Finally."
    chloe "Wait."
    narrator "Chloe looks toward the hallway."
    chloe "You hear that?"
    narrator "Silence."
    ethan "I didn't hear anything."
    michael "Probably just the pipes."
    narrator "Chloe shrugs."
    chloe "Yeah, probably."
    narrator "We turn off the lights."

    jump chapter_2