# ethan
image ethanintear = "images/ethan/ethanintear.png"
image ethanangrytalk = "images/ethan/ethanangrytalk.png"
image ethancrying = "images/ethan/ethancrying.png"
image ethandisturbed = "images/ethan/ethandisturbed.png"
image ethanlaughtalk = "images/ethan/ethanlaughtalk.png"
image ethanneutralquiet = "images/ethan/ethanneutralquiet.png"
image ethanquietsmile = "images/ethan/ethansmilequiet.png"
image ethansadquiet = "images/ethan/ethansadquiet.png"
image ethansadtalk = "images/ethan/ethansadtalk.png"
image ethansweating = "images/ethan/ethansweating.png"
image ethansmilequiet = "images/ethan/ethansmilequiet.png"
# chloe
image chloeneutralquiet = "images/ethan/chloe/chloeneutralquiet.png"
image chloeneutraltalk = "images/ethan/chloe/chloeneutraltalk.png"
image chloesmilequiet = "images/ethan/chloe/chloesmilequiet.png"
image chloesmiletalk = "images/ethan/chloe/chloesmiletalk.png"
image chloetongueout = "images/ethan/chloe/chloetongueout.png"
# michael
image michaeldisturbed = "images/ethan/michael/michaeldisturbed.png"
image michaelintears = "images/ethan/michael/michaelintears.png"
image michaelneutralquiet = "images/ethan/michael/michaelneutralquiet.png"
image michaelsmilequiet = "images/ethan/michael/michaelsmilequiet.png"
image michaelsmiletalk = "images/ethan/michael/michaelsmiletalk.png"
image michaelupsettalk = "images.ethan/michael/michaelupsettalk.png"